### ISSUE TITLE
Please add RSS feed

### ISSUE THREAD

**Issue by nitinthewiz** [gavinhenderson/gavinhenderson.github.io#2]
Hey Gavin,

I found Awesome Personal blogs and realized there's no RSS feed list (OPML file) in the repo, so I'm adding one. I noticed that your blog doesn't have an RSS feed, simply because you've not added the feed plugin to it.

I found that the way to do it is pretty simple - https://github.com/jekyll/jekyll-feed

Could you please add a feed and then update the OPML file? (I've not submitted it yet to the awesome personal blogs repo, will do it soon)

**Comment by gavinhenderson** [comment]
@nitinthewiz The feed is available at https://gavinhenderson.me/feed.xml now

**Comment by nitinthewiz** [comment]
Excellent! Thank you! I've updated the OPML file. Once the PR is accepted, it'll show up on the main repo - https://github.com/nitinthewiz/awesome-personal-blogs/blob/master/blogfeeds.opml
